### ISSUE TITLE
注册时机改成在AppDelegate的load方法中统一管理不是更好些吗？

### ISSUE THREAD

**Issue by niehaili** [alexsun/MLSOAppDelegate#2]
你好，现在的注册都是放在了各个服务类中，如果把注册时机放在了AppDelegate中的load方法里面，增删功能时，岂不是更方便管理吗？？不知道我的这种想法是否有什么问题呢？或者说你这种设计有其他原因呢？

**Comment by orchidFang** [comment]
@niehaili  现在框架中实现的是各个服务的自注册，如果我要增加或删除某个服务，只需要把相应的服务文件加入或者踢出工程就可以了，不需要改任何代码，而像你所说的注册时间放到AppDelegate的load方法中的话，增删的时候就需要修改代码，更加麻烦、复杂、易出错。所以说框架中的这种插件式的架构更加优秀。

**Comment by niehaili** [comment]
按照你这种解释，还是会有问题的，各个服务的先后执行顺序就不受控制了，比如说我想先执行国际化的服务，再执行rootUI的服务，但是却事与愿违。--

**Comment by orchidFang** [comment]
@niehaili 这个框架中各个服务的先后执行顺序确实是不受控制的。。可以看readme。。

**Comment by niehaili** [comment]
好的，谢谢
